[package]
name = "test-rust-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.1"
sqlx = { version = "0.8.0", features = [
    "bigdecimal",
    "mysql",
    "runtime-tokio",
    "time",
] }
tokio = { version = "1.39.2", features = ["full"] }
