version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=product
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql